name: Web CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 'current', 'latest' ]
    name: Build on Node ${{ matrix.Node }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node ${{ matrix.Node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.Node }}

      - name: Install NPM Packages
        working-directory: web
        run: npm install

      - name: Build frontend
        working-directory: web
        run: npm run build

      # TODO: upload artifacts
