name: Kotlin CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Build on Java ${{ matrix.Java }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build --no-daemon

      - name: Upload API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: "api/build/distributions/*.zip" # TODO: does ktor support shadowing?

      - name: Upload Discord Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vodchat
          path: "discord/build/libs/*-all.jar"

      - name: Upload Reddit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vodthread
          path: "reddit/build/libs/*-all.jar"